"""initial_schema

Revision ID: 60915c4a5513
Revises: 
Create Date: 2026-04-05 05:16:54.574874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60915c4a5513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bandit_state', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listening_history', 'played_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_history_played_at', table_name='listening_history')
    op.create_index('idx_history_played_at', 'listening_history', ['played_at'], unique=False)
    op.drop_column('listening_history', 'completion_pct')
    op.drop_constraint('playlist_tracks_playlist_id_song_id_key', 'playlist_tracks', type_='unique')
    op.alter_column('playlists', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendations', 'recommended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_recs_type_date', table_name='recommendations')
    op.create_index('idx_recs_type_date', 'recommendations', ['rec_type', 'recommended_at'], unique=False)
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('songs', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('songs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('songs', 'added_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('sessions', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('idx_recs_type_date', table_name='recommendations')
    op.create_index('idx_recs_type_date', 'recommendations', ['rec_type', sa.text('recommended_at DESC')], unique=False)
    op.alter_column('recommendations', 'recommended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('playlists', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('playlist_tracks_playlist_id_song_id_key', 'playlist_tracks', ['playlist_id', 'song_id'])
    op.add_column('listening_history', sa.Column('completion_pct', sa.DOUBLE_PRECISION(precision=53), sa.Computed('\nCASE\n    WHEN (song_duration_ms > 0) THEN (((play_duration_ms)::double precision / (song_duration_ms)::double precision) * (100)::double precision)\n    ELSE NULL::double precision\nEND', persisted=True), autoincrement=False, nullable=True))
    op.drop_index('idx_history_played_at', table_name='listening_history')
    op.create_index('idx_history_played_at', 'listening_history', [sa.text('played_at DESC')], unique=False)
    op.alter_column('listening_history', 'played_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bandit_state', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
